name: "Build container"
"on":
  workflow_dispatch:
  push:
    paths-ignore:
      - docs/**
    branches:
      - main
  pull_request:

permissions:
  contents: read
  packages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      output: image
      push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      cache: true
      platforms: linux/amd64,linux/arm64
      meta-images: ghcr.io/${{ github.repository }}
      meta-tags: |
        type=raw,value=latest
        type=ref,event=branch
        type=ref,event=tag
        type=ref,event=pr
      build-args: |
        GITHUB_SHA=${{ github.sha }}
        DESCRIPTION="Rusty little S3-compatible object storage server"
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
